### ISSUE TITLE
Implement devcontainer for students

### ISSUE THREAD

**Issue by StoneyJackson** [HFOSSedu/GitKit#15]
So inside the devcontainer, to complete the activities, students need...

* Git
* GitHub
* Meld
* Modify files in the project

**Comment by StoneyJackson** [comment]
@braughtg For the GitKit, do students need to run FarmData2?

**Comment by StoneyJackson** [comment]
Here is an example of configuring a devcontainer to run and access GUI apps in the devcontainer ... https://gitlab.com/hfossedu/teaching-with-development-containers/gui-example

**Comment by braughtg** [comment]
> @braughtg For the GitKit, do students need to run FarmData2?

No, they do not need to run FarmData2 or any of the testing tools for the GitKit.

**Comment by StoneyJackson** [comment]
Solved by #27
